#!/usr/bin/env python3
"""Assemble the repo into paste-ready bot templates under dist/.

The repo is the source of truth; dist/ is a build artifact that happens to be
committed, so the templates are readable on GitHub without cloning. Run this
after changing any skill, routine, or instruction file:

    python3 tools/build_template.py            # write dist/
    python3 tools/build_template.py --check    # fail if dist/ is stale

It refuses to write if anything token-shaped is present, because dist/ is the
file people copy and paste into a public template.
"""
import argparse, hashlib, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"

# Which bot owns which skills. A companion never gets a Canvas data source —
# canvas-core, grade-paste or ics-feed. It has no token and no feed URL, so
# shipping it a reader would be a lie the first call exposes.
OWNERSHIP = {
    "registrar": {
        "instructions": "bot/INSTRUCTIONS.md",
        "skills": ["canvas-core", "grade-paste", "ics-feed", "grade-model",
                   "daily-brief", "deadline-guard", "announcement-digest",
                   "group-project-tracker", "weekly-retro", "calendar-sync",
                   "connector-core", "handoff"],
        "routines": ["morning-brief", "deadline-48h", "deadline-24h", "grade-watch",
                     "announcements", "group-check", "weekly-retro"],
    },
    "tutor": {
        "instructions": "bots/tutor/INSTRUCTIONS.md",
        "skills": ["study-engine", "drive-archive", "connector-core", "handoff"],
        "routines": ["study-drip"],
    },
    "advocate": {
        "instructions": "bots/advocate/INSTRUCTIONS.md",
        "skills": ["extension-email", "mail-draft", "office-hours-finder",
                   "syllabus-ingest", "connector-core", "handoff"],
        "routines": [],
    },
}

# Solo mode: with no companions installed the Registrar runs everything itself.
SOLO_EXTRA = ["study-engine", "extension-email", "mail-draft", "office-hours-finder",
              "syllabus-ingest", "drive-archive"]

CONNECTORS = {
    "registrar": ["Google Calendar (optional)"],
    "tutor": ["Google Drive (optional)"],
    "advocate": ["Gmail (optional, drafts only)", "Google Drive (optional)"],
}

SECRET = re.compile(r"[0-9]{4}~[A-Za-z0-9]{20,}|feeds/calendars/user_[A-Za-z0-9]{10,}"
                    r"|Bearer\s+[A-Za-z0-9_\-]{16,}")
RULE = "\n\n" + "-" * 72 + "\n\n"


def read(rel):
    return (ROOT / rel).read_text().rstrip() + "\n"


def strip_frontmatter(text):
    """Skill files carry YAML frontmatter for the repo; the paste block keeps it,
    since that is how a skill declares its name and description."""
    return text


def build_bot(name, solo=False):
    spec = OWNERSHIP[name]
    skills = list(spec["skills"])
    if solo:
        skills += [s for s in SOLO_EXTRA if s not in skills]

    out = {}
    out["INSTRUCTIONS.md"] = read(spec["instructions"])

    parts = [f"# Skills for the {name.title()}",
             "",
             f"{len(skills)} skills. Each block below is one skill — paste them as "
             f"separate skills, not as one.",
             ""]
    for s in sorted(skills):
        parts.append(f"## skills/{s}")
        parts.append("")
        parts.append(read(f"skills/{s}/SKILL.md").rstrip())
        if s == "canvas-core":
            parts.append("")
            parts.append("### canvas-core: no-HTTP fallback")
            parts.append("")
            parts.append(read("skills/canvas-core/NO_HTTP_FALLBACK.md").rstrip())
        parts.append(RULE.strip())
    out["SKILLS.md"] = "\n".join(parts).rstrip() + "\n"

    if spec["routines"]:
        rparts = [f"# Routines for the {name.title()}", "",
                  f"{len(spec['routines'])} routines.", ""]
        for r in spec["routines"]:
            rparts.append(f"## routines/{r}")
            rparts.append("")
            rparts.append(read(f"routines/{r}.md").rstrip())
            rparts.append(RULE.strip())
        out["ROUTINES.md"] = "\n".join(rparts).rstrip() + "\n"
    return out


def manifest():
    lines = ["# Install manifest", "",
             "Generated by `tools/build_template.py`. Do not edit by hand.", "",
             "Install the **Registrar** first. It is the whole product on its own;",
             "the companions are optional and can wait until you want them.", ""]
    for name in ("registrar", "tutor", "advocate"):
        spec = OWNERSHIP[name]
        n_sk = len(spec["skills"]) + (len(SOLO_EXTRA) if name == "registrar" else 0)
        lines += [f"## {name.title()}",
                  "",
                  f"- Instructions: `dist/{name}/INSTRUCTIONS.md`",
                  f"- Skills: `dist/{name}/SKILLS.md` "
                  f"({n_sk if name == 'registrar' else len(spec['skills'])} blocks)",
                  (f"- Routines: `dist/{name}/ROUTINES.md` ({len(spec['routines'])})"
                   if spec["routines"] else "- Routines: none"),
                  f"- Connectors: {', '.join(CONNECTORS[name]) or 'none'}",
                  ""]
        if name == "registrar":
            lines += ["The Registrar's bundle includes the companion skills too, so a",
                      "solo install has every feature. If you later add the Tutor or",
                      "the Advocate, the Registrar hands that work over instead of",
                      "doing it itself — nothing needs removing.", ""]
        else:
            lines += [f"**Requires the Registrar.** Installed alone it has no Canvas",
                      "access and nothing to do.", ""]
    return "\n".join(lines).rstrip() + "\n"


def generate():
    files = {"MANIFEST.md": manifest()}
    for name in OWNERSHIP:
        for fn, body in build_bot(name, solo=(name == "registrar")).items():
            files[f"{name}/{fn}"] = body
    return files


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if dist/ differs from a fresh build")
    args = ap.parse_args()

    files = generate()

    leaked = {p: SECRET.search(b).group(0)[:12] for p, b in files.items()
              if SECRET.search(b)}
    if leaked:
        print("REFUSING TO BUILD — secret-shaped strings in the output:")
        for p, frag in leaked.items():
            print(f"  {p}: {frag}...")
        return 2

    if args.check:
        stale = []
        for rel, body in files.items():
            f = DIST / rel
            if not f.exists() or f.read_text() != body:
                stale.append(rel)
        extra = [str(p.relative_to(DIST)) for p in DIST.rglob("*.md")
                 if str(p.relative_to(DIST)) not in files] if DIST.exists() else []
        if stale or extra:
            print("dist/ is stale. Run: python3 tools/build_template.py")
            for p in stale:
                print(f"  differs/missing: {p}")
            for p in extra:
                print(f"  orphaned:        {p}")
            return 1
        print(f"dist/ is up to date ({len(files)} files)")
        return 0

    for rel, body in files.items():
        f = DIST / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(body)
    total = sum(len(b) for b in files.values())
    print(f"wrote {len(files)} files to dist/  ({total:,} chars)")
    for rel in sorted(files):
        h = hashlib.sha256(files[rel].encode()).hexdigest()[:8]
        print(f"  {h}  {len(files[rel]):>7,}  dist/{rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
